version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: messmate
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=4001
    ports:
      - '4001:4001'
    depends_on:
      - db

  app:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    depends_on:
      - server

volumes:
  db-data:
