import { type VoteOption } from './votingBlueprints';

export const LUNCH_CATALOG: VoteOption[] = [
  { id: 'L01', comboId: 'L01', label: 'Tomato Pappu + Potato Fry + Pepper Rasam + Gongura Pachadi', emoji: '🥣', items: ['Tomato Pappu', 'Potato Fry', 'Pepper Rasam', 'Gongura Pachadi'], category: 'lunch_combo', family: 'Potato', subFamilies: ['TomatoPappu', 'Rasam', 'Gongura'] },
  { id: 'L02', comboId: 'L02', label: 'Palakura Pappu + Beans Fry + Tomato Rasam + Kandi Pachadi', emoji: '🥬', items: ['Palakura Pappu', 'Beans Fry', 'Tomato Rasam', 'Kandi Pachadi'], category: 'lunch_combo', family: 'Beans', subFamilies: ['LeafyPappu', 'Rasam', 'Kandi'] },
  { id: 'L03', comboId: 'L03', label: 'Gongura Pappu + Dondakaya Fry + Garlic Rasam + Palli Pachadi', emoji: '🌿', items: ['Gongura Pappu', 'Dondakaya Fry', 'Garlic Rasam', 'Palli Pachadi'], category: 'lunch_combo', family: 'Dondakaya', subFamilies: ['LeafyPappu', 'Rasam', 'Palli'] },
  { id: 'L04', comboId: 'L04', label: 'Dosakaya Pappu + Aratikaya Fry + Jeera Rasam + Tomato Pachadi', emoji: '🥒', items: ['Dosakaya Pappu', 'Aratikaya Fry', 'Jeera Rasam', 'Tomato Pachadi'], category: 'lunch_combo', family: 'Aratikaya', subFamilies: ['TangyPappu', 'Rasam', 'Tomato'] },
  { id: 'L05', comboId: 'L05', label: 'Mamidikaya Pappu + Vankaya Fry + Tomato Charu + Kobbari Pachadi', emoji: '🥭', items: ['Mamidikaya Pappu', 'Vankaya Fry', 'Tomato Charu', 'Kobbari Pachadi'], category: 'lunch_combo', family: 'Vankaya', subFamilies: ['TangyPappu', 'Charu', 'Kobbari'] },
  { id: 'L06', comboId: 'L06', label: 'Muddapappu + Aloo 65 + Coriander Rasam + Allam Pachadi', emoji: '🥣', items: ['Muddapappu', 'Aloo 65', 'Coriander Rasam', 'Allam Pachadi'], category: 'lunch_combo', family: 'Potato', subFamilies: ['PlainPappu', 'Rasam', 'Allam'] },
  { id: 'L07', comboId: 'L07', label: 'Beerakaya Pappu + Cabbage Curry + Curry Leaf Rasam + Beerakaya Pachadi', emoji: '🥒', items: ['Beerakaya Pappu', 'Cabbage Curry', 'Curry Leaf Rasam', 'Beerakaya Pachadi'], category: 'lunch_combo', family: 'Beerakaya', subFamilies: ['PlainPappu', 'Rasam', 'Beerakaya'] },
  { id: 'L08', comboId: 'L08', label: 'Chukkakura Pappu + Chamagadda Fry + Garlic Rasam + Tomato Onion Pachadi', emoji: '🌿', items: ['Chukkakura Pappu', 'Chamagadda Fry', 'Garlic Rasam', 'Tomato Onion Pachadi'], category: 'lunch_combo', family: 'Chamagadda', subFamilies: ['LeafyPappu', 'Rasam', 'Tomato'] },
  { id: 'L09', comboId: 'L09', label: 'Bachalikura Pappu + Potato Mint Fry + Coriander Rasam + Pudina Pachadi', emoji: '🍃', items: ['Bachalikura Pappu', 'Potato Mint Fry', 'Coriander Rasam', 'Pudina Pachadi'], category: 'lunch_combo', family: 'Potato', subFamilies: ['LeafyPappu', 'Rasam', 'Pudina'] },
  { id: 'L10', comboId: 'L10', label: 'Thotakura Pappu + Bendakaya Fry + Pepper Rasam + Dosakaya Pachadi', emoji: '🥬', items: ['Thotakura Pappu', 'Bendakaya Fry', 'Pepper Rasam', 'Dosakaya Pachadi'], category: 'lunch_combo', family: 'Bendakaya', subFamilies: ['LeafyPappu', 'Rasam', 'Dosakaya'] },
  { id: 'L11', comboId: 'L11', label: 'Methi Pappu + Carrot Beans Curry + Tomato Rasam + Nuvvula Pachadi', emoji: '🌿', items: ['Methi Pappu', 'Carrot Beans Curry', 'Tomato Rasam', 'Nuvvula Pachadi'], category: 'lunch_combo', family: 'Carrot/Beans', subFamilies: ['LeafyPappu', 'Rasam', 'Nuvvula'] },
  { id: 'L12', comboId: 'L12', label: 'Pesarapappu + Dondakaya Fry + Jeera Rasam + Palli Pachadi', emoji: '🥣', items: ['Pesarapappu', 'Dondakaya Fry', 'Jeera Rasam', 'Palli Pachadi'], category: 'lunch_combo', family: 'Dondakaya', subFamilies: ['PlainPappu', 'Rasam', 'Palli'] },
  { id: 'L13', comboId: 'L13', label: 'Tomato Pappu + Capsicum Curry + Garlic Rasam + Onion Pachadi', emoji: '🥣', items: ['Tomato Pappu', 'Capsicum Curry', 'Garlic Rasam', 'Onion Pachadi'], category: 'lunch_combo', family: 'Capsicum', subFamilies: ['TomatoPappu', 'Rasam', 'Onion'] },
  { id: 'L14', comboId: 'L14', label: 'Gongura Pappu + Gutti Vankaya + Ulava Charu + Kandi Pachadi', emoji: '🌿', items: ['Gongura Pappu', 'Gutti Vankaya', 'Ulava Charu', 'Kandi Pachadi'], category: 'lunch_combo', family: 'Vankaya', subFamilies: ['LeafyPappu', 'Charu', 'Kandi'] },
  { id: 'L15', comboId: 'L15', label: 'Dosakaya Pappu + Beans Coconut Curry + Curry Leaf Rasam + Kobbari Pachadi', emoji: '🥒', items: ['Dosakaya Pappu', 'Beans Coconut Curry', 'Curry Leaf Rasam', 'Kobbari Pachadi'], category: 'lunch_combo', family: 'Beans', subFamilies: ['TangyPappu', 'Rasam', 'Kobbari'] },
  { id: 'L16', comboId: 'L16', label: 'Mamidikaya Pappu + Crispy Potato Fry + Tomato Charu + Allam Pachadi', emoji: '🥭', items: ['Mamidikaya Pappu', 'Crispy Potato Fry', 'Tomato Charu', 'Allam Pachadi'], category: 'lunch_combo', family: 'Potato', subFamilies: ['TangyPappu', 'Charu', 'Allam'] },
  { id: 'L17', comboId: 'L17', label: 'Palakura Pappu + Beetroot Curry + Jeera Rasam + Carrot Pachadi', emoji: '🥬', items: ['Palakura Pappu', 'Beetroot Curry', 'Jeera Rasam', 'Carrot Pachadi'], category: 'lunch_combo', family: 'Beetroot', subFamilies: ['LeafyPappu', 'Rasam', 'Carrot'] },
  { id: 'L18', comboId: 'L18', label: 'Muddapappu + Vankaya Masala + Coriander Rasam + Vankaya Pachadi', emoji: '🥣', items: ['Muddapappu', 'Vankaya Masala', 'Coriander Rasam', 'Vankaya Pachadi'], category: 'lunch_combo', family: 'Vankaya', subFamilies: ['PlainPappu', 'Rasam', 'Vankaya'] },
  { id: 'L19', comboId: 'L19', label: 'Beerakaya Pappu + Aratikaya Fry + Pepper Rasam + Beerakaya Tomato Pachadi', emoji: '🥒', items: ['Beerakaya Pappu', 'Aratikaya Fry', 'Pepper Rasam', 'Beerakaya Tomato Pachadi'], category: 'lunch_combo', family: 'Aratikaya', subFamilies: ['PlainPappu', 'Rasam', 'Beerakaya'] },
  { id: 'L20', comboId: 'L20', label: 'Chukkakura Pappu + Mixed Veg Curry + Tomato Rasam + Pudina Pachadi', emoji: '🌿', items: ['Chukkakura Pappu', 'Mixed Veg Curry', 'Tomato Rasam', 'Pudina Pachadi'], category: 'lunch_combo', family: 'MixedVeg', subFamilies: ['LeafyPappu', 'Rasam', 'Pudina'] },
  { id: 'L21', comboId: 'L21', label: 'Bachalikura Pappu + Aloo Fry + Garlic Rasam + Gongura Pachadi', emoji: '🍃', items: ['Bachalikura Pappu', 'Aloo Fry', 'RunCommand Rasam', 'Gongura Pachadi'], category: 'lunch_combo', family: 'Potato', subFamilies: ['LeafyPappu', 'Rasam', 'Gongura'] },
  { id: 'L22', comboId: 'L22', label: 'Thotakura Pappu + Cabbage Coconut Curry + Curry Leaf Rasam + Kobbari Pachadi', emoji: '🥬', items: ['Thotakura Pappu', 'Cabbage Coconut Curry', 'Curry Leaf Rasam', 'Kobbari Pachadi'], category: 'lunch_combo', family: 'Cabbage', subFamilies: ['LeafyPappu', 'Rasam', 'Kobbari'] },
  { id: 'L23', comboId: 'L23', label: 'Pesarapappu + Bendakaya Fry + Jeera Rasam + Palli Pachadi', emoji: '🥣', items: ['Pesarapappu', 'Bendakaya Fry', 'Jeera Rasam', 'Palli Pachadi'], category: 'lunch_combo', family: 'Bendakaya', subFamilies: ['PlainPappu', 'Rasam', 'Palli'] },
  { id: 'L24', comboId: 'L24', label: 'Ulava Pappu + Gutti Vankaya + Ulava Charu + Kandi Pachadi', emoji: '🥣', items: ['Ulava Pappu', 'Gutti Vankaya', 'Ulava Charu', 'Kandi Pachadi'], category: 'lunch_combo', family: 'Vankaya', subFamilies: ['PlainPappu', 'Charu', 'Kandi'] },
];

export const NON_VEG_CURRY_OPTIONS: VoteOption[] = [
  { id: 'nv-chicken-curry', comboId: 'nv-chicken-curry', label: 'Chicken Curry', emoji: '🍗', items: ['Chicken Curry'], category: 'non_veg_curry', dietPreference: 'non_veg' },
  { id: 'nv-pepper-chicken', comboId: 'nv-pepper-chicken', label: 'Pepper Chicken', emoji: '🌶️', items: ['Pepper Chicken'], category: 'non_veg_curry', dietPreference: 'non_veg' },
  { id: 'nv-egg-curry',     comboId: 'nv-egg-curry',     label: 'Egg Curry',     emoji: '🥚', items: ['Egg Curry'],     category: 'non_veg_curry', dietPreference: 'non_veg' },
];
